name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/lib/**"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # 4. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run semantic-release
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub 토큰 자동 제공
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # NPM 배포를 위한 NPM 토큰
        run: npx semantic-release
        working-directory: packages/lib
